import React, { useState } from "react";
import FormField from "./FormField";
import preview from "../assets/preview.png";
import { getSurprisePrompt,Loader } from "../utitlis/index.js";
export default function CreatePost() {
  const [generatingImage, setGeneratingImage] = useState(false);
  const [shareImage, setShareImage] = useState(false);
  const [loading, setLoading] = useState(false);

  const [form, setForm] = useState({
    name: "Hamza",
    prompt: "A comic book cover of a superhero wearing headphones",
    photo: null,
  });

  const handleGenerate = (event) => {
    event.preventDefault();
    setGeneratingImage(true);
    console.log("Generating");
  };

  const handleChange = (event) => {
    setForm({ ...form, [event.target.name]: [event.target.value] });
    console.log("Changing");
  };
  const handleSupriseMe = (event) => {
    event.preventDefault()
    console.log("Surprise Me");
    const randomPrompt = getSurprisePrompt(form.prompt)
    setForm({...form,prompt:randomPrompt})
  };

  return (
    <div className="flex flex-col md:w-[65%] md:mt-[4%] md:mx-auto">
      <div className="w-[100%] ">
        <h1 className="font-bold text-2xl tracking-wide">Create</h1>
        <p className="text-sm mt-2 text-gray-500">
          Create the imaginative and visullay stunning images generated by
          DALL-E AI and share them with the Community.
        </p>
      </div>

      <form className="mt-[5%] flex flex-col gap-y-5" onSubmit={handleGenerate}>
        <FormField
          labelName={"Your Name"}
          name="name"
          placeholder={"Hamza"}
          value={form.name}
          handleChange={handleChange}
          handleSupriseMe={handleSupriseMe}
        />
        <FormField
          labelName={"Prompt"}
          name="prompt"
          isSupriseMe
          placeholder={"Hamza"}
          value={form.prompt}
          type="text"
          handleChange={handleChange}
          handleSupriseMe={handleSupriseMe}
        />
        <div className="relative overflow-hidden  flex items-center p-3 h-[35%] w-[35%] justify-center  border border-blue-500/50">
          {form.photo ? (
            <img
              className="z-[100] w-full h-full object-contain"
              src={form.photo}
              alt={form.prompt}
            />
          ) : (
            <img
              className="z-[100] w-full h-full object-contain "
              src={preview}
              alt={form.prompt}
            />
          )}

          {generatingImage && (
            <div className="absolute flex justify-center items-center  z-0 overflow-visible top-0 w-[100%] h-[100%] bg-gray-500">
              <Loader />
            </div>
          )}
        </div>
        <div>
          <button
            type="submit"
            className={
              "text-center w-[150px] rounded cursor-pointer" +
              (generatingImage
                ? " h-[44px] border-2 border-gray-400 text-gray-700"
                : " h-[40px] bg-blue-700 border-0  border-blue-700 text-white hover:bg-white hover:border-2 hover:text-blue-700 active:bg-blue-700  active:text-white")
            }
            disabled={generatingImage ? true : false}
          >
            {generatingImage ? "Generating..." : "Generate"}
          </button>
        </div>
      </form>
      <div className="flex flex-col">
        <h2 className="mb-4 text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
          Once you have created the image you can share it with others in the cmmunity
        </h2>
        <div className="">
          <button
            type="submit"
            className={
              "text-center w-full rounded cursor-pointer" +
              (generatingImage
                ? " h-[44px] border-2 border-gray-400 text-gray-700"
                : " h-[40px] bg-green-700 border-0  border-green-700 text-white hover:bg-white hover:border-2 hover:text-green-700 active:bg-green-700  active:text-white")
            }
            disabled={shareImage ? true : false}
          >
            {shareImage ? "Sharing..." : "Share Images with Community"}
          </button>
        </div>
      </div>
    </div>
  );
}
